name: Sync to Gitee

on:
  push:
    branches: [ master ]  # 监听 master 分支的 push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录

      - name: Configure SSH for Gitee
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/gitee_key
          chmod 600 ~/.ssh/gitee_key
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      - name: Set Git Identity
        run: |
          git config --global user.name "Github Action"  # 保留，不需要修改
          git config --global user.email "action@github.com"  # 保留，不需要修改

      - name: Add Gitee Remote
        run: |
          git remote add gitee git@gitee.com:${{ secrets.GITEE_REPO }}.git

      - name: Push to Gitee
        run: |
          git push gitee master:master --force
        env:
          SSH_AGENT_PID: ""
          SSH_AUTH_SOCK: ""
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/gitee_key"
