name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Configure Git
        run: |
          git config --global user.name "GithubAction"  # 保留，不需要修改
          git config --global user.email "action@github.com"  # 保留，不需要修改

      - name: Add Gitee Remote
        run: |
          git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_REPO }}.git

      - name: Push to Gitee
        run: git push gitee --tags --force

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x ./build_package.sh

      - name: Build package
        run: ./build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: readme.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/linux-artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-release-to-gitee:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-artifacts
          path: artifacts

      - name: Create Gitee Release
        run: |
          TAG_NAME="${{ github.ref_name }}"

          RELEASE_INFO=$(curl -X POST 'https://gitee.com/api/v5/repos/${{ secrets.GITEE_REPO }}/releases' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: token ${{ secrets.GITEE_TOKEN }}' \
          -d '{
            "tag_name": "$TAG_NAME",
            "target_commitish": "master",
            "name": "Release $TAG_NAME",
            "body": "$TAG_NAME",
            "draft": false,
            "prerelease": false
          }')
          echo $RELEASE_INFO

          RELEASE_ID=$(echo "$RELEASE_INFO" | jq -r '.id')
          echo $RELEASE_ID

          find artifacts -type f | while read -r file_path; do
              echo "| $file_path"
              curl -X POST "https://gitee.com/api/v5/repos/${{ secrets.GITEE_REPO }}/releases/$RELEASE_ID/attach_files" \
          -H "Authorization: token ${{ secrets.GITEE_TOKEN }}" \
          -F "file=@$file_path"
            done
          done
