name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  releases: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Configure Git
        run: |
          git config --global user.name "GithubAction"  # 保留，不需要修改
          git config --global user.email "action@github.com"  # 保留，不需要修改

      - name: Add Gitee Remote
        run: |
          git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_REPO }}.git

      - name: Push to Gitee
        run: git push gitee --tags --force

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x ./build_package.sh

      - name: Build package
        run: ./build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: readme.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/linux-artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-to-gitee:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Sync Release to Gitee
        uses: wangyoucao577/go-release-action@v1.53
        with:
          gitee_token: ${{ secrets.GITEE_TOKEN }}
          gitee_owner: "KyleLittlek"
          gitee_repo: "sync-to-gitee"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          asset_path: "artifacts/**/*"
