name: Sync to Gitee

on:
  push:
    branches:
      - master  # 只同步master分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的提交历史

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.GITEE_PRIVATE_KEY }}

      - name: Add Gitee remote
        run: |
          git remote add gitee ${{ secrets.GITEE_REPO }}
          git config --global user.name "GitHub Action"  # 保留，不需要修改
          git config --global user.email "action@github.com"  # 保留，不需要改

      - name: Push to Gitee
        run: git push gitee master --force    
